package com.whitelistchecker.domain.telegram

enum class DetailedReportTextKey {
    TITLE,
    FINAL_STATE,
    SITE_SIGNAL,
    DNS_SIGNAL,
    CHECKED_NETWORK,
    ACTIVE_NETWORK,
    PRIVATE_DNS,
    PRIVATE_DNS_SERVER,
    CUSTOM_DNS,
    FOREIGN_SITES_SUMMARY,
    LOCAL_SITES_SUMMARY,
    FOREIGN_DNS_SUMMARY,
    LOCAL_DNS_SUMMARY,
    CHECK_TIME,
    TCP_DIAGNOSTICS,
    ERROR,
    DNS_NOT_RUN,
    DNS_HEADER,
    FOREIGN_DNS_GROUP,
    LOCAL_DNS_GROUP,
    DNS_SERVER,
    PROTOCOL,
    STATUS,
    RESPONSE_TIME,
    RESOLVED_ADDRESS_COUNT,
    ERROR_TYPE,
    SITES_NOT_RUN,
    SITES_HEADER,
    FOREIGN_SITES_GROUP,
    LOCAL_SITES_GROUP,
    SITE,
    HTTP,
    UNAVAILABLE_HEADER,
    UNAVAILABLE_SITE,
    EVENT,
    OLD_STATE,
    NEW_STATE,
    EVENT_TIME,
    ACTIVE,
    INACTIVE,
    USED,
    NOT_USED,
    AVAILABLE,
    UNAVAILABLE,
    NOT_AVAILABLE,
}

interface DetailedReportTextProvider {
    fun text(
        key: DetailedReportTextKey,
        vararg args: Any,
    ): String
}
