package com.whitelistchecker.domain.statistics

enum class StatisticsConsistencyWarningCode {
    CHECK_RUNS_WITHOUT_SUMMARY,
    TOTAL_RUNS_EXCEEDS_HISTORY,
    OUTCOME_SUM_EXCEEDS_TOTAL,
    TARGET_STATS_WITHOUT_TARGET_RESULTS,
    LAST_RUN_IN_FUTURE,
    STATISTICS_UPDATED_BEFORE_LAST_RUN,
    INVALID_SUCCESS_RATE,
    INVALID_AVERAGE_LATENCY,
    NEGATIVE_CONSECUTIVE_FAILURES,
}
